{{- include "ffc-helm-library.container-config-map" (list . "ffc-techspike-function-taskmanager.config-map") -}}
{{- define "ffc-techspike-function-taskmanager.config-map" -}}
data:
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  FUNCTIONS_WORKER_RUNTIME: {{ quote .Values.container.functionsWorkerRuntime }}
{{- end -}}
