environment: production
environmentCode:
name: ffc-techspike-function-taskmanager
namespace: ffc-techspike
workstream: ffc-techspike
image: ffc-techspike-function-taskmanager

labels: {}

aadPodIdentity: true

appInsights:
  key:

azureIdentity:
  clientID:
  resourceID:

containerConfigMap:
  name: ffc-techspike-function-taskmanager-config-map

containerSecret:
  name: ffc-techspike-function-taskmanager-secret
  type: Opaque

deployment:
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 1
  priorityClassName: default
  replicas: 1
  restartPolicy: Always

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3000
  azureWebJobsStorage:
  functionsWorkerRuntime: dotnet-isolated

service:
  port: 80
  type: ClusterIP

ingress:
  class: nginx
  endpoint: ffc-techspike-authentication
  server: example.com

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3